//student module action type
export const GET_STUDENT_DATA_REQUEST="GET_STUDENT_DATA_REQUEST";
export const GET_STUDENT_DATA_SUCCESS="GET_STUDENT_DATA_SUCCESS";
export const GET_STUDENT_DATA_ERROR="GET_STUDENT_DATA_ERROR";

export const ADD_STUDENT_DATA_REQUEST="ADD_STUDENT_DATA_REQUEST";
export const ADD_STUDENT_DATA_SUCCESS="ADD_STUDENT_DATA_SUCCESS";
export const ADD_STUDENT_DATA_ERROR="ADD_STUDENT_DATA_ERROR";

export const UPDATE_STUDENT_DATA_REQUEST="UPDATE_STUDENT_DATA_REQUEST";
export const UPDATE_STUDENT_DATA_SUCCESS="UPDATE_STUDENT_DATA_SUCCESS";
export const UPDATE_STUDENT_DATA_ERROR="UPDATE_STUDENT_DATA_ERROR";

export const DELETE_STUDENT_DATA_REQUEST="DELETE_STUDENT_DATA_REQUEST";
export const DELETE_STUDENT_DATA_SUCCESS="DELETE_STUDENT_DATA_SUCCESS";
export const DELETE_STUDENT_DATA_ERROR="DELETE_STUDENT_DATA_ERROR";

// Feedback module action type
export const GET_FEEDBACK_REQUEST=" GET_FEEDBACK_REQUEST";
export const GET_FEEDBACK_SUCCESS=" GET_FEEDBACK_SUCCESS";
export const GET_FEEDBACK_ERROR=" GET_FEEDBACK_ERROR";

export const DELETE_FEEDBACK_REQUEST=" DELETE_FEEDBACK_REQUEST";
export const DELETE_FEEDBACK_SUCCESS=" DELETE_FEEDBACK_SUCCESS";
export const DELETE_FEEDBACK_ERROR=" DELETE_FEEDBACK_ERROR";

export const ADD_FEEDBACK_REQUEST="ADD_FEEDBACK_REQUEST";
export const ADD_FEEDBACK_SUCCESS="ADD_FEEDBACK_SUCCESS";
export const ADD_FEEDBACK_ERROR="ADD_FEEDBACK_ERROR";

export const UPDATE_FEEDBACK_REQUEST="UPDATE_FEEDBACK_REQUEST";
export const UPDATE_FEEDBACK_SUCCESS="UPDATE_FEEDBACK_SUCCESS";
export const UPDATE_FEEDBACK_ERROR="UPDATE_FEEDBACK_ERROR";


//User module action type
export const GET_USER_REQUEST=" GET_USER_REQUEST";
export const GET_USER_SUCCESS=" GET_USER_SUCCESS";
export const GET_USER_ERROR=" GET_USER_ERROR";

export const DELETE_USER_REQUEST=" DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS=" DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR=" DELETE_USER_ERROR";

export const ADD_USER_REQUEST="ADD_USER_REQUEST";
export const ADD_USER_SUCCESS="ADD_USER_SUCCESS";
export const ADD_USER_ERROR="ADD_USER_ERROR";

export const UPDATE_USER_REQUEST="UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS="UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR="UPDATE_USER_ERROR";


//question module action type
export const GET_QUESTION_REQUEST=" GET_QUESTION_REQUEST";
export const GET_QUESTION_SUCCESS=" GET_QUESTION_SUCCESS";
export const GET_QUESTION_ERROR=" GET_QUESTION_ERROR";

export const DELETE_QUESTION_REQUEST=" DELETE_QUESTION_REQUEST";
export const DELETE_QUESTION_SUCCESS=" DELETE_QUESTION_SUCCESS";
export const DELETE_QUESTION_ERROR=" DELETE_QUESTION_ERROR";

export const ADD_QUESTION_REQUEST="ADD_QUESTION_REQUEST";
export const ADD_QUESTION_SUCCESS="ADD_QUESTION_SUCCESS";
export const ADD_QUESTION_ERROR="ADD_QUESTION_ERROR";

export const UPDATE_QUESTION_REQUEST="UPDATE_QUESTION_REQUEST";
export const UPDATE_QUESTION_SUCCESS="UPDATE_QUESTION_SUCCESS";
export const UPDATE_QUESTION_ERROR="UPDATE_QUESTION_ERROR";

//Voucher module action type
export const GET_VOUCHER_REQUEST=" GET_VOUCHER_REQUEST";
export const GET_VOUCHER_SUCCESS=" GET_VOUCHER_SUCCESS";
export const GET_VOUCHER_ERROR=" GET_VOUCHER_ERROR";

//Result module action type
export const GET_RESULT_REQUEST=" GET_RESULT_REQUEST";
export const GET_RESULT_SUCCESS=" GET_RESULT_SUCCESS";
export const GET_RESULT_ERROR=" GET_RESULT_ERROR";

export const DELETE_RESULT_REQUEST=" DELETE_RESULT_REQUEST";
export const DELETE_RESULT_SUCCESS=" DELETE_RESULT_SUCCESS";
export const DELETE_RESULT_ERROR=" DELETE_RESULT_ERROR";




